name: Build website

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup cache for Zola executable
        id: cache-zola
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/zola
          key: zola-v0.17.2

      - name: Install Zola
        if: steps.cache-zola.outputs.cache-hit != 'true'
        run: |
          wget -q -O - 'https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz' | tar xzf - -C /usr/local/bin

      - name: Configure Git
        run: |
          git config user.name "Publisher"
          git config user.email "publisher@users.noreply.github.com"

      - name: Switch to branch 'gh-pages'
        run: |
          git branch -f gh-pages HEAD
          git checkout gh-pages

      - name: Generate HTML
        run: zola build

      - name: Publish generated HTML
        run: |
          cp CNAME public/
          git add --force public/

          # Only commit and push if there are staged changes.
          git diff --staged --quiet || git commit -m "Publish" && git push -f origin `git subtree split -P public`:refs/heads/gh-pages
